apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerpipe.fullname" . }}-secret-env-vars
  labels:
    {{- include "powerpipe.labels" . | nindent 4 }}
stringData:
    POWERPIPE_DATABASE: postgres://steampipe:{{ .Values.global.steampipeDatabasePassword }}@{{ include "steampipe.fullname" . }}:9193/steampipe
    PGDATABASE: "steampipe"
    PGHOST: "127.0.0.1"
    PGPASSWORD: {{ .Values.global.steampipeDatabasePassword }}
    PGUSER: "steampipe"
    PGPORT: "9193"
    {{- if .Values.powerpipe.secretEnvVars }}
    {{- toYaml .Values.powerpipe.secretEnvVars | nindent 2 }}
    {{- end }}
