{{- if .Values.powerpipe.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "powerpipe.serviceAccountName" . }}
  labels:
    {{- include "powerpipe.labels" . | nindent 4 }}
  {{- with .Values.powerpipe.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
