apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerpipe.fullname" . }}-secret-env-vars
  labels:
    {{- include "powerpipe.labels" . | nindent 4 }}
stringData:
    POWERPIPE_DATABASE: postgres://steampipe:abcd1234@steampipe:9193/steampipe
