# .Values should define which path to mount these files to 
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steampipe.fullname" . }}-secret
  labels:
    {{- include "steampipe.labels" . | nindent 4 }}
stringData:
    KUBECONFIG: |
      example kubeconfig
    AWS_CREDENTIALS: |
      [account_a]
      aws_access_key_id = AKIA4YFAKEKEYXTDS252
      aws_secret_access_key = SH42YMW5p3EThisIsNotRealzTiEUwXN8BOIOF5J8m
      region = us-west-2

      [account_b]
      aws_access_key_id = AKIA4YFAKEKEYJ7HS98F
      aws_secret_access_key = Apf938vDKd8ThisIsNotRealzTiEUwXj9nKLWP9mg4