apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steampipe.fullname" . }}-secret-env-vars
  labels:
    {{- include "steampipe.labels" . | nindent 4 }}
stringData:
  STEAMPIPE_DATABASE_PASSWORD: {{ .Values.global.steampipeDatabasePassword }}
  {{- if .Values.powerpipe.secretEnvVars }}
  {{- toYaml .Values.steampipe.secretEnvVars | nindent 2 }}
  {{- end }}

