apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steampipe.fullname" . }}-secret
  labels:
    {{- include "steampipe.labels" . | nindent 4 }}
stringData:
    STEAMPIPE_DATABASE_PASSWORD: "abcd1234"