{{- $steampipeConfig := .Values.steampipe.config | default (dict) -}}
# every key: data here will be mounted to ./steampipe/config/* 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "steampipe.fullname" . }}-config
  labels:
    {{- include "steampipe.labels" . | nindent 4 }}
{{- if eq (len $steampipeConfig) 0 }}
data: {}
{{- else }}
data: {{ toYaml $steampipeConfig | nindent 2 }}
{{- end }}
