apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steampipe.fullname" . }}-credentials
  labels:
    {{- include "steampipe.labels" . | nindent 4 }}
{{- if eq (len (.Values.steampipe.secretCredentials | default (dict))) 0 }}
stringData: {}
{{- else }}
stringData:
{{- range $config := .Values.steampipe.secretCredentials }}
  {{ $config.name }}: | {{ $config.content | nindent 4}}
{{- end }}
{{- end }}

