apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "steampipe.fullname" . }}-cm-env-vars
  labels:
    {{- include "steampipe.labels" . | nindent 4 }}
data:
  INSTALL_PLUGINS: "steampipe kubernetes"
