apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "steampipe.fullname" . }}
  labels:
    {{- include "steampipe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.steampipe.replicaCount }}
  selector:
    matchLabels:
      {{- include "steampipe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.steampipe.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "steampipe.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.steampipe.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "steampipe.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.steampipe.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "steampipe.fullname" . }}
          envFrom:
          - configMapRef:
              name: {{ include "steampipe.fullname" . }}-cm-env-vars
          - secretRef:
              name: {{ include "steampipe.fullname" . }}-secret-env-vars
          securityContext:
            {{- toYaml .Values.steampipe.securityContext | nindent 12 }}
          image: "{{ .Values.steampipe.image.repository }}:{{ .Values.steampipe.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.steampipe.image.pullPolicy }}
          #command: ["sleep", "3000"]
          ports:
            - name: http
              containerPort: {{ .Values.steampipe.containerPort }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - bash
              - ./healthcheck.sh
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          resources:
            {{- toYaml .Values.steampipe.resources | nindent 12 }}
          volumeMounts:
          - name: steampipe-config-volume
            mountPath: /app/.steampipe/config/aws.spc
            subPath: aws.spc
          - name: steampipe-config-volume
            mountPath: /app/.steampipe/config/kubernetes.spc
            subPath: kubernetes.spc
          - name: steampipe-config-volume
            mountPath: /app/.steampipe/config/gcp.spc
            subPath: gcp.spc
      volumes:
      - name: steampipe-config-volume
        configMap:
          name: {{ include "steampipe.fullname" . }}-config
          optional: true
          defaultMode: 0777
          items:
            - key: aws.spc
              path: aws.spc  # same as subPath
            - key: kubernetes.spc
              path: kubernetes.spc  # same as subPath
            - key: gcp.spc
              path: gcp.spc  # same as subPath
      {{- with .Values.steampipe.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.steampipe.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.steampipe.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
