name: Build and publish a steampipe and powerpipe images to ghcr.io
on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [ published ]

  # push:
  #   branches:
  #     - 'main'
  #   paths:
  #     - 'steampipe/**'
  #     - 'powerpipe/**'
  #     - '.github/workflows/docker-publish.yaml'

env:
  REGISTRY: ghcr.io
  STEAMPIPE_IMAGE_NAME: ${{ github.repository }}--steampipe
  POWERPIPE_IMAGE_NAME: ${{ github.repository }}--powerpipe

jobs:
  build-and-push-steampipe-and-powerpipe-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: steampipemeta
        uses: docker/metadata-action@v4
        with:
          images:  ${{ env.REGISTRY }}/${{ env.STEAMPIPE_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image -- steampipe
        uses: docker/build-push-action@v4
        with:
          context: ./steampipe
          push: true
          tags: ${{ steps.steampipemeta.outputs.tags }}
          labels: ${{ steps.steampipemeta.outputs.labels }}
          file: ./steampipe/Dockerfile
          build-args: STEAMPIPE_BINARY_DOWNLOAD_URL=https://github.com/turbot/steampipe/releases/download/v0.24.2/steampipe_linux_amd64.tar.gz

      - name: Extract metadata (tags, labels) for Docker
        id: powerpipemeta
        uses: docker/metadata-action@v4
        with:
          images:  ${{ env.REGISTRY }}/${{ env.POWERPIPE_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image -- powerpipe
        uses: docker/build-push-action@v4
        with:
          context: ./powerpipe
          push: true
          tags: ${{ steps.powerpipemeta.outputs.tags }}
          labels: ${{ steps.powerpipemeta.outputs.labels }}
          file: ./powerpipe/Dockerfile
          build-args: POWERPIPE_BINARY_DOWNLOAD_URL=https://github.com/turbot/powerpipe/releases/download/v0.4.4/powerpipe.linux.amd64.tar.gz
