name: Build and publish a steampipe and powerpipe images to ghcr.io

on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  # release:
  #   types: [ published ]

  push:
    tags:
      - "v*.*.*"

# Prevent concurrent workflows for the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  STEAMPIPE_IMAGE_NAME: ${{ github.repository }}--steampipe
  POWERPIPE_IMAGE_NAME: ${{ github.repository }}--powerpipe
  DOCKER_BUILDKIT: 1  # Enable BuildKit for better performance

jobs:
  build-and-push-steampipe-and-powerpipe-docker-images:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Add timeout to prevent hanging workflows
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated from v3
        # with:
        #   fetch-depth: 0  # Fetch all history for better versioning

      - name: Save tag to file
        run: echo "${GITHUB_REF#refs/tags/}" > release_tag.txt

      - name: Upload tag as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-tag
          path: release_tag.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Added for better build performance

      - name: Log in to the Container registry
        uses: docker/login-action@v3  # Updated from v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq  # Using apt-get instead of snap for better reliability

      - name: Extract metadata (tags, labels) for Docker
        id: steampipemeta
        uses: docker/metadata-action@v5  # Updated from v4
        with:
          images:  ${{ env.REGISTRY }}/${{ env.STEAMPIPE_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha,format=short

      - name: Find Latest Steampipe Release Version
        id: latest_steampipe_release
        run: |
          STEAMPIPE_LATEST_VERSION=$(curl -s --fail https://api.github.com/repos/turbot/steampipe/releases/latest | jq -r '.tag_name')
          if [ -z "$STEAMPIPE_LATEST_VERSION" ]; then
            echo "Failed to get Steampipe release version"
            exit 1
          fi
          echo "STEAMPIPE_LATEST_VERSION=$STEAMPIPE_LATEST_VERSION"
          echo "latest_version=$STEAMPIPE_LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image -- steampipe
        uses: docker/build-push-action@v5  # Updated from v4
        with:
          context: ./steampipe
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.steampipemeta.outputs.tags }}
          labels: ${{ steps.steampipemeta.outputs.labels }}
          file: ./steampipe/Dockerfile
          build-args: STEAMPIPE_VERSION=${{ steps.latest_steampipe_release.outputs.latest_version}}
          cache-from: type=gha  # Enable GitHub Actions cache
          cache-to: type=gha,mode=max
          provenance: true  # Enable provenance attestation
          sbom: true  # Enable SBOM generation

      - name: Find Latest Powerpipe Release Version
        id: latest_powerpipe_release
        run: |
          POWERPIPE_LATEST_VERSION=$(curl -s --fail https://api.github.com/repos/turbot/powerpipe/releases/latest | jq -r '.tag_name')
          if [ -z "$POWERPIPE_LATEST_VERSION" ]; then
            echo "Failed to get Powerpipe release version"
            exit 1
          fi
          echo "POWERPIPE_LATEST_VERSION=$POWERPIPE_LATEST_VERSION"
          echo "latest_version=$POWERPIPE_LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: powerpipemeta
        uses: docker/metadata-action@v5  # Updated from v4
        with:
          images:  ${{ env.REGISTRY }}/${{ env.POWERPIPE_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha,format=short

      - name: Build and push Docker image -- powerpipe
        uses: docker/build-push-action@v5  # Updated from v4
        with:
          context: ./powerpipe
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.powerpipemeta.outputs.tags }}
          labels: ${{ steps.powerpipemeta.outputs.labels }}
          file: ./powerpipe/Dockerfile
          build-args: POWERPIPE_VERSION=${{ steps.latest_powerpipe_release.outputs.latest_version}}
          cache-from: type=gha  # Enable GitHub Actions cache
          cache-to: type=gha,mode=max
          provenance: true  # Enable provenance attestation
          sbom: true  # Enable SBOM generation

      - name: Save dependency versions to artifact
        run: |
          echo "STEAMPIPE_VERSION=${{ steps.latest_steampipe_release.outputs.latest_version }}" > dependency_versions.txt
          echo "POWERPIPE_VERSION=${{ steps.latest_powerpipe_release.outputs.latest_version }}" >> dependency_versions.txt

      - name: Upload dependency versions as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-versions
          path: dependency_versions.txt
