name: Helm package and push to ghcr.io
on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  # release:
  #   types: [ published ]

  push:
    branches:
      - 'main'
    paths:
      - 'helm-chart/**'
      - '.github/workflows/helm-package-and-publish.yaml'
env:
  REGISTRY: ghcr.io
  HELM_REPO_NAME: ${{ github.repository }}--helm-chart

jobs:
  build-and-push-balcony-terraform-import-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - uses: chrisdickinson/setup-yq@latest
      
      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Configure functions
        run: |
          PACKAGE_OUTPUT=$(helm package --version 1.0.0 helm-chart)
          PACKAGE_NAME=$(basename $PACKAGE_OUTPUT)
          echo "Generated helm package: $PACKAGE_NAME"
          echo ${{ secrets.GHCR_TOKEN }} | helm registry login ghcr.io/oguzhan-yilmaz --username oguzhan-yilmaz --password-stdin
          helm push "$PACKAGE_NAME"" oci://ghcr.io/oguzhan-yilmaz