name: Helm package and push to ghcr.io
on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [ published ]

  # push:
  #   branches:
  #     - 'main'
  #   paths:
  #     - 'helm-chart/**'
  #     - '.github/workflows/helm-package-and-publish.yaml'

# TODO: 
#   - package helm
#   - upload release artifact
#   - get its url
#   - update/merge gh-pages/index.yaml


jobs:
  helm-package-and-push-to-ghcr-io:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Helm Package and Push to ghcr.io
        id: helm_package
        run: |
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          VERSION="${RELEASE_TAG:-v6.6.6}"
          CLEAN_VERSION="${VERSION#v}"
          echo "RELEASE Version: $CLEAN_VERSION"
          PACKAGE_OUTPUT=$(helm package --version "$CLEAN_VERSION" helm-chart)
          echo "PACKAGE_OUTPUT=$PACKAGE_OUTPUT"
          PACKAGE_NAME=$(basename "$PACKAGE_OUTPUT")
          echo "Generated helm package: $PACKAGE_NAME"
          # save the generated package name to github_output to pass it to next step
          echo "package-name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
      
      - name: test
        id: test
        run: |
          echo "message=$MESSAGE"
        env:
          MESSAGE: ${{ steps.helm_package.outputs.package-name}}

      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: ${{ steps.helm_package.outputs.package-name}}
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: ${{ steps.helm_package.outputs.package-name}}
          if-no-files-found: error

