name: Helm package and push to ghcr.io
on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  # release:
  #   types: [ published ]

  push:
    branches:
      - 'main'
    paths:
      - 'helm-chart/**'
      - '.github/workflows/helm-package-and-publish.yaml'
env:
  REGISTRY: ghcr.io
  HELM_REPO_NAME: ${{ github.repository }}--helm-chart

jobs:
  helm-package-and-push-to-ghcr-io:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Helm Package and Push to ghcr.io
        run: |
          PACKAGE_OUTPUT=$(helm package --version 1.0.0 helm-chart)
          echo "PACKAGE_OUTPUT=$PACKAGE_OUTPUT"
          PACKAGE_NAME=$(basename "$PACKAGE_OUTPUT")
          echo "Generated helm package: $PACKAGE_NAME"
          echo ${{ secrets.GHCR_TOKEN }} | helm registry login ghcr.io/oguzhan-yilmaz/steampipe-powerpipe-kubernetes --username oguzhan-yilmaz --password-stdin
          helm push "$PACKAGE_NAME" oci://ghcr.io/oguzhan-yilmaz