name: Helm package and push to ghcr.io
on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  # release:
  #   types: [ published ]

  push:
    branches:
      - 'main'
    paths:
      - 'helm-chart/**'
      - '.github/workflows/helm-package-and-publish.yaml'

# TODO: 
#   - package helm
#   - upload release artifact
#   - get its url
#   - update/merge gh-pages/index.yaml


jobs:
  helm-package-and-push-to-ghcr-io:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Helm Package and Push to ghcr.io
        id: helm_package
        run: |
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          VERSION="${RELEASE_TAG:-'v6.6.6'}"
          CLEAN_VERSION="${VERSION#v}"
          echo "RELEASE Version: $CLEAN_VERSION"
          PACKAGE_OUTPUT=$(helm package --version "$CLEAN_VERSION" helm-chart)
          echo "PACKAGE_OUTPUT=$PACKAGE_OUTPUT"
          PACKAGE_NAME=$(basename "$PACKAGE_OUTPUT")
          echo "Generated helm package: $PACKAGE_NAME"
          echo "package-name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
      - name: test
        id: test
        run: |

          echo "message=$MESSAGE"
        env:
          MESSAGE: ${{ steps.helm_package.outputs.package-name}}

      #   with:
      #     # Name of the artifact to upload.
      #     # Optional. Default is 'artifact'
      #     name:

      #     # A file, directory or wildcard pattern that describes what to upload
      #     # Required.
      #     path:

      #     # The desired behavior if no files are found using the provided path.
      #     # Available Options:
      #     #   warn: Output a warning but do not fail the action
      #     #   error: Fail the action with an error message
      #     #   ignore: Do not output any warnings or errors, the action does not fail
      #     # Optional. Default is 'warn'
      #     if-no-files-found:

      #     # Duration after which artifact will expire in days. 0 means using default retention.
      #     # Minimum 1 day.
      #     # Maximum 90 days unless changed from the repository settings page.
      #     # Optional. Defaults to repository settings.
      #     retention-days:

      #     # The level of compression for Zlib to be applied to the artifact archive.
      #     # The value can range from 0 to 9.
      #     # For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.
      #     # Optional. Default is '6'
      #     compression-level:

      #     # If true, an artifact with a matching name will be deleted before a new one is uploaded.
      #     # If false, the action will fail if an artifact for the given name already exists.
      #     # Does not fail if the artifact does not exist.
      #     # Optional. Default is 'false'
      #     overwrite:

      #     # Whether to include hidden files in the provided path in the artifact
      #     # The file contents of any hidden files in the path should be validated before
      #     # enabled this to avoid uploading sensitive information.
      #     # Optional. Default is 'false'
      #     include-hidden-files: